import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Snake Game</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="./favicon.png" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <Link href="/game">Snake Game!</Link>
          </h1>
        </main>
      </div>

      <footer className={styles.footer}>
        <Link href="https://www.chaos131.com/">
          <span className={styles.logo}>
            <Image src="./chaos131.png" alt="CHAOS 131" width={110} height={30} />
          </span>
        </Link>
      </footer>
    </>
  )
}

export default Home
